# env: MountainCar-v0
# n_episodes: 2000000
# agent:
#   __type__: SarsaAgent
#   epsilon: 0.0
#   gamma: 1.0
#   alpha: 0.5
#   n_bins: 10


env: Pendulum-v1
n_episodes: 2000000
vizualization_freq: 1000
agent:
  __type__: SarsaAgent
  epsilon: 0.01
  gamma: 0.95 
  alpha: 0.8
  n_bins: 32
  action_bins: 5